apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: excal
spec:
  rules:
  - host: excal.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: excal
            port:
              number: 8080
